Repository MISP/misp-docker, pull requests merged in 2025-01, with the labels that each got.

#202 Include rsyslog for local syslogger
  core/Dockerfile
  core/files/etc/supervisor/conf.d/10-supervisor.conf
Labels: enhancement

#171 Update Backup info in README.md
  README.md
Labels: documentation

#204 Remove doubled X-XSS-Protection Header
  core/files/etc/nginx/includes/misp
Labels: enhancement, question
